import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppProvider, ThemeProvider } from "@/components/ThemeProvider";
import Header from "@/components/Header";
import { Toaster } from "@/components/ui/toaster";
import { Footer } from "@/components/Footer"
import { Toaster as Sonner } from "@/components/ui/sonner"
import NavbarVertical from "@/components/NavbarVertical";
import { cn } from "@/lib/utils";
const inter = Inter({ subsets: ["vietnamese"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head></head>
      <body className={cn(inter.className, 'overflow-hidden')} suppressHydrationWarning={true} >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <AppProvider>
            {/* <Header /> */}
            <div className="flex min-h-screen w-full flex-col overflow-hidden">
              <NavbarVertical />
              <div className="flex flex-col">
                <main className="grid flex-1 items-start">
                  <div className="flex min-h-screen w-full flex-col">
                    <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-14">
                      <div className="grid auto-rows-max items-start gap-4 md:gap-8 lg:col-span-2 px-6 h-[772px]">
                        {children}
                        <Footer />
                      </div>
                    </div>
                    <Sonner />
                    <Toaster />
                  </div>
                </main>
              </div>
            </div>
          </AppProvider>
        </ThemeProvider>
      </body>
    </html >
  );
}
